before_script:
- npm install -g cordova ionic
- npm install
script: ionic build
language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_0c73d57bebb9_key -iv $encrypted_0c73d57bebb9_iv
  -in keys.js.enc -out keys.js -d
